### ISSUE TITLE
Install on Mycroft Mark 1 fails

### ISSUE THREAD

**Issue by cooljimy84** [OpenVoiceOS/ovos-installer#338]
I followed the guide on https://community.openconversational.ai/t/howto-begin-your-open-voice-os-journey-with-the-ovos-installer/14900/1
but ran into a few issues.

The image on Rpi-imager is "Pi OS lite (64bit) Bookworm 2025-05-13"
I tried upgrading and rebooting before installing, after seeing [https://github.com/OpenVoiceOS/ovos-installer/issues/104](url)
Not upgrading before installing
Enabling I2C in the raspi-config menu before the install

https://pastebin.com/3DQYsEYr

**Comment by goldyfruit** [comment]
Do you have any Pi Hole or AdGuards? If yes, just allow the artifacts.smartgic.io and whl.smartgic.io which are hosted in my basement _(so home IP address)_

**Comment by cooljimy84** [comment]
> Do you have any Pi Hole or AdGuards? If yes, just allow the artifacts.smartgic.io and whl.smartgic.io which are hosted in my basement _(so home IP address)_

I do, but the logs say it wasn't blocked. I've added it and am rerunning the normal installer now, i can also run with -d again if that helps more ?

**Comment by cooljimy84** [comment]
Running as the installer as normal (from the guide)

gives me this summary page

                        │                                                                                        │ 
                        │     - OS:       Debian 12 (bookworm)                                                   │ 
                        │     - Kernel:   6.12.25+rpt-rpi-v8                                                     │ 
                        │     - RPi:      Raspberry Pi 3 Model B Rev 1.2                                         │ 
                        │     - Python:   3.11                                                                   │ 
                        │     - AVX/SIMD: true                                                                   │ 
                        │     - Hardware: N/A                                                                    │ 
                        │     - Venv:     /home/pi/.venvs/ovos-installer                                         │ 
                        │     - Sound:    PulseAudio (on PipeWire)                                               │ 
                        │     - Display:  N/A          

and this log file

```
pi@mk1:~ $ cat /var/log/ovos-installer.log 
utils/common.sh: line 150: docker: command not found
utils/common.sh: line 153: podman: command not found
[aarch64, 6.12.25+rpt-rpi-v8, 3.11, debian, 12]
/usr/sbin/iw
Already have PKG_NAME='python3'
Already have PKG_NAME='python3-dev'
Already have PKG_NAME='python3-pip'
Already have PKG_NAME='python3-venv'
Already have PKG_NAME='whiptail'
Already have PKG_NAME='expect'
Already have PKG_NAME='jq'
Already have PKG_NAME='i2c-tools'
Already have PKG_NAME='iw'
No missing packages
Collecting uv>=0.4.10
  Downloading uv-0.8.18-py3-none-manylinux_2_28_aarch64.whl (19.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 11.7 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.8.18
Using Python 3.11.2 environment at: /home/pi/.venvs/ovos-installer
Resolved 2 packages in 148ms
Downloading pip (1.7MiB)
Downloading setuptools (1.1MiB)
 Downloading pip
 Downloading setuptools
Prepared 2 packages in 560ms
Uninstalled 2 packages in 185ms
Installed 2 packages in 48ms
 - pip==23.0.1
 + pip==25.2
 - setuptools==66.1.1
 + setuptools==80.9.0
Using Python 3.11.2 environment at: /home/pi/.venvs/ovos-installer
Resolved 16 packages in 558ms
Downloading cryptography (4.1MiB)
Downloading ansible (49.2MiB)
Downloading ansible-core (2.1MiB)
 Downloading cryptography
 Downloading ansible-core
 Downloading ansible
Prepared 16 packages in 19.88s
Installed 16 packages in 4.03s
 + ansible==10.7.0
 + ansible-core==2.17.14
 + certifi==2025.8.3
 + cffi==2.0.0
 + charset-normalizer==3.4.3
 + cryptography==46.0.1
 + docker==7.1.0
 + idna==3.10
 + jinja2==3.1.6
 + markupsafe==3.0.2
 + packaging==25.0
 + pycparser==2.23
 + pyyaml==6.0.2
 + requests==2.32.3
 + resolvelib==1.0.1
 + urllib3==2.5.0
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ansible-posix-2.0.0.tar.gz to /root/.ansible/tmp/ansible-local-834c_3slpdf/tmp1ni6665z/ansible-posix-2.0.0-_i9tsst6
Installing 'ansible.posix:2.0.0' to '/root/.ansible/collections/ansible_collections/ansible/posix'
ansible.posix:2.0.0 was installed successfully
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-docker-4.6.1.tar.gz to /root/.ansible/tmp/ansible-local-834c_3slpdf/tmp1ni6665z/community-docker-4.6.1-nks_0dhd
Installing 'community.docker:4.6.1' to '/root/.ansible/collections/ansible_collections/community/docker'
community.docker:4.6.1 was installed successfully
'community.library_inventory_filtering_v1:1.0.2' is already installed, skipping.
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-general-10.7.1.tar.gz to /root/.ansible/tmp/ansible-local-834c_3slpdf/tmp1ni6665z/community-general-10.7.1-vupm6m16
Installing 'community.general:10.7.1' to '/root/.ansible/collections/ansible_collections/community/general'
community.general:10.7.1 was installed successfully
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/kewlfft-aur-0.11.1.tar.gz to /root/.ansible/tmp/ansible-local-834c_3slpdf/tmp1ni6665z/kewlfft-aur-0.11.1-d21ahnt0
Installing 'kewlfft.aur:0.11.1' to '/root/.ansible/collections/ansible_collections/kewlfft/aur'
kewlfft.aur:0.11.1 was installed successfully
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/moreati-uv-0.0.3.tar.gz to /root/.ansible/tmp/ansible-local-834c_3slpdf/tmp1ni6665z/moreati-uv-0.0.3-2rneneow
Installing 'moreati.uv:0.0.3' to '/root/.ansible/collections/ansible_collections/moreati/uv'
moreati.uv:0.0.3 was installed successfully
DTOVERLAY[debug]: using platform 'bcm2835'
DTOVERLAY[debug]: overlay map loaded
run_cmd: which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre
run_cmd: dtc -I fs -O dtb -o '/tmp/.dtoverlays/base.dtb' /proc/device-tree 1>/dev/null 2>&1
DTOVERLAY[debug]: loading file '/tmp/.dtoverlays/base.dtb'
DTOVERLAY[debug]: found override i2c_arm
DTOVERLAY[debug]:   override i2c_arm: string target 'status'
DTOVERLAY[debug]: wrote 162 bytes to '/tmp/.dtoverlays/0_dtparam.dtbo'
DTOVERLAY[debug]: wrote 174 bytes to '/sys/kernel/config/device-tree/overlays/0_dtparam/dtbo'
run_cmd: which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post
avrdude warning: System wide configuration file version ()
        does not match Avrdude build version (7.3-20240428 (37ac6eba))
avrdude warning: programmer linuxgpio overwrites previous definition /usr/local/etc/avrdude.conf:3. [/home/pi/.avrduderc:3]
using libgpiod for linuxgpio

avrdude error: no port has been specified on the command line or in the config file
        specify a port using the -P option and try again

true
true
true
false
false
pi@mk1:~ $ 

```

with -d it ends as normal, saying it completed, the log file show the same error at the end as above (i can include if you want)

**Comment by goldyfruit** [comment]
Do you have this file https://artifacts.smartgic.io/avrdude/avrdude.conf?

**Comment by cooljimy84** [comment]
yep
```
pi@mk1:~ $ sudo find / -name avrdude.conf
/usr/local/etc/avrdude.conf
```

If it helps, my mk1 was one of the first few off the line, s/n 000601 Mycroft Mark 1
even if i edit the tui/detection.sh file to force it to always retrun "Mycroft Mark 1" still the speaker/mic/eyes/knob don't work

**Comment by cooljimy84** [comment]
Not sure if i'm helping but avrdude is expecting "-P /dev/gpiochip0" on line 493 of "ovos-installer/utils/common.sh"
if i run 
```
sudo ./avrduderc -p atmega328p -c linuxgpio -U signature:r:-:i -F -P /dev/gpiochip0
```
the eyes full up and then start spinning again, but the command returns
```
avrduderc warning: System wide configuration file version ()
          does not match Avrdude build version (7.3-20240428 (37ac6eba))
using libgpiod for linuxgpio

avrduderc error: AVR part atmega328p not found

Valid parts are:


avrduderc done.  Thank you.
```
From a quick look the script is looking to get back some info ATMEGA328P_SIGNATURE=":030000001E950F3B" but it doesn't get anything back.

Sorry if this doesn't help, i'll keep trying to work through it, but i'm not a coder, just used to working through issues from log files.

**Comment by goldyfruit** [comment]
I will have to plug my Mark 1 again to test the `ovos-installer`, on common issue is the daughter board not being properly attached to the Raspberry Pi or maybe some corrosion on the pins.

**Comment by cooljimy84** [comment]
I'll try the original Mycroft installer as I reseated all the boards a while ago. But I'll also reseat the boards

**Comment by cooljimy84** [comment]
Just flashed the 2021 Mycroft AI image to an sdcard and running DEMO (by holding down the button and selecting demo) works fine.

**Comment by goldyfruit** [comment]
So I pushed few fixes:
- Re-compile `avrdude` 8.1 _(instead for 7.3)_ with `libgpiod` support
- Tweaked the `.avrduderc`
- Fix the `avrdude.conf`

It is now working for me again with the latest commit of `ovos-installer` and a fresh Raspberry Pi OS Bookworm Lite 64-bit updated to the latest packages.

<img width="1921" height="1081" alt="Image" src="https://github.com/user-attachments/assets/14384535-70e9-45e9-8ab7-bfffced60acb" />

**Comment by goldyfruit** [comment]
Just run a full install successfully.

<img width="1921" height="1081" alt="Image" src="https://github.com/user-attachments/assets/24c0d321-9434-4ee3-82c7-65f6ed4e4e58" />

```
goldyfruit@mark1:~$ systemctl --user list-units *ovos* 
  UNIT                         LOAD   ACTIVE SUB     DESCRIPTION                        
  ovos-audio.service           loaded active running Open Voice OS - Audio
  ovos-core.service            loaded active running Open Voice OS - Core (skills)
  ovos-ggwave-listener.service loaded active running Open Voice OS - ggwave listener
  ovos-listener.service        loaded active running Open Voice OS - Listener
  ovos-messagebus.service      loaded active running Open Voice OS - Message bus service
  ovos-phal.service            loaded active running Open Voice OS - PHAL
  ovos.service                 loaded active exited  Open Voice OS - Meta service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
7 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
```

**Comment by cooljimy84** [comment]
Fresh install, with nothing updated (just ran sudo apt update a few times to update the repos, but not upgrade any thing)
failed after asking to scan the I2C bus
https://paste.uoi.io/4MDP

after enabling I2C and SPI in the raspi-config and rerunning it still fails
https://paste.uoi.io/HiBj

this is after doing a apt upgrade and reboot
https://paste.uoi.io/tbW1

a manual install of "sudo apt install libhidapi-libusb0" gets the installer to detect and install as a mk1.
and a reboot after the install gets everything working !

It's a bit laggy, but working well.

**Comment by goldyfruit** [comment]
The `raspi-config` is not required, the `ovos-installer` does it automaticaly.

I compiled `avrdude` with the `HID` & `USB` support which is why `libhidapi-libusb0` package is required, you should not have any error now.

Yeah OVOS will be laggy on Mark 1 as is it running a Raspberry Pi 3B, but they are ways :)
Have a look here: https://www.youtube.com/watch?v=Q6FAo_gPRms
